### PR TITLE
Add the role-has-responsible-party constraint #703

### PR DESCRIPTION
**Pull request by DimitriZhurkin**
# Committer Notes

1. Modified role-has-responsible-party-FAIL.yaml
2. Added ssp-role-has-responsible-party-INVALID.xml

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Comment by aj-stein-gsa** [comment]
I am having a little trouble rebasing this locally to guide what to do, but I will update later today, @DimitriZhurkin.

**Comment by DimitriZhurkin** [comment]
> I am having a little trouble rebasing this locally to guide what to do, but I will update later today, @DimitriZhurkin.

@aj-stein-gsa, the constraint proper is in #703. This PR adds the modified `role-has-responsible-party-FAIL.yaml` and `ssp-role-has-responsible-party-INVALID.xml`.

**Comment by aj-stein-gsa** [comment]
> > I am having a little trouble rebasing this locally to guide what to do, but I will update later today, @DimitriZhurkin.
> 
> @aj-stein-gsa, the constraint proper is in #703. This PR adds the modified `role-has-responsible-party-FAIL.yaml` and `ssp-role-has-responsible-party-INVALID.xml`.

I totally midunderstood and thought 703 was an issue, not an additional PR, thank you!

**Comment by aj-stein-gsa** [comment]
I might need to work with you to explain how to update your branch that is in a PR. There are two ways

1. One of your branches in a PR to a remote upstream (GSA/fedramp-automation) here and another branch need to combine, but both branches are on your repo. You have kind of picked this approach. You would need to PR _in your fork_ from one branch to another, and then the pre-existing branch in the PR will get updated. To do that [this URL will set it up so you press the green button and start the PR](https://github.com/DimitriZhurkin/fedramp-automation/compare/feature/add-role-has-responsible-part...DimitriZhurkin:fedramp-automation:feature/add-role-has-responsible-party). That said, I would not think that helps.
2. Just push changes in your second branch directly into the other branch you control in your own fork because you can.

```sh
git fetch --all
git checkout feature/add-role-has-responsible-part # Notice the y is missing, this is the branch for the 703 PR
git merge DimitriZhurkin/feature/add-role-has-responsible-party # Merge in 751 branch PR code into 703 branch
git push origin
```

I would go for Option 2, and in either case you will need to close this PR. DM me later in the afternoon to discuss. You may still have merge conflicts somehow (I can use the URL from 1, even if I do not create the PR, just to spot check). So maybe we need to talk about that.

**Comment by DimitriZhurkin** [comment]
AJ, let's close both #703 and #751. I'll create a new PR for the role-has-responsible-party constraint.

**Comment by aj-stein-gsa** [comment]
OK, sounds good, @DimitriZhurkin, I am also here to help you work issues with updating that PR as needed. Don't be a stranger and DM me if needed.

**Comment by DimitriZhurkin** [comment]
> OK, sounds good, @DimitriZhurkin, I am also here to help you work issues with updating that PR as needed. Don't be a stranger and DM me if needed.

Hmm, pushed `Add role-has-responsible-party constraint` to my fork, and I don't see it. Has anything changed in the process?

**Comment by DimitriZhurkin** [comment]
OK, created the `Add role-has-responsible-party constraint` #754 pull request.

We may close #703 and #751.

**Pull request closed without merging**
