### PR TITLE
Feature/hotfix 

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

hotfix constraints and add sample content for better coverage on using resolved profiles and multiple data-flow diagrams

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Review by DimitriZhurkin — APPROVED** [review]
Nicely done!

**Comment by Gabeblis** [comment]
What issue is this part of? Is this related to the work done in #991?

**Comment by wandmagic** [comment]
> What issue is this part of? Is this related to the work done in #991?

I noticed this issue when validating the telos SSP, so i thought it would be good to fix it

**Comment by wandmagic** [comment]
these constraints crash when there are multiple links for these items

**Comment by wandmagic** [comment]
I have added some extra sample content to help us cover this use case
https://github.com/GSA/fedramp-automation/issues/993

I wasn't able to reproduce the error, but content pointing to this profile is now included in the test suite

**Comment by Gabeblis** [comment]
This was handled in PR #991 as part of issue #940

**Comment by wandmagic** [comment]
> This was handled in PR #991 as part of issue #940

ok right on

**Pull request closed without merging**
