### PR TITLE
add oscal server

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

introduce oscal-server  implements #719
### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- ~If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?~

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Review by aj-stein-gsa — COMMENTED** [review]
Can you update the checklist? Is this against an issue or some necessary cleanup, or both?

**Comment by aj-stein-gsa** [comment]
Sorry to be "that guy" but re the checklist, what issue does the PR relate to? We have that one checked off.

**Comment by wandmagic** [comment]
> Sorry to be "that guy" but re the checklist, what issue does the PR relate to? We have that one checked off.

#719

**Comment by wandmagic** [comment]
thanks @Gabeblis  for the suggestion to add documentation

**Review by Gabeblis — APPROVED** [review]
This all looks good. The code changes and the documentation look solid. I like how you included the different options, how to run everything, and best practices/performance considerations/troubleshooting. I ran this locally and didn't find any issues. This is great work!

**Review by Rene2mt — APPROVED** [review]

**Review by Rene2mt — APPROVED** [review]

**Pull request merged**
