### PR TITLE
Feature oscal server

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

Introduce oscal server (toggled by ) ENV variable OSCAL_EXECUTOR

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Review by aj-stein-gsa — COMMENTED** [review]
Sorry there are some cert issues and it is slow to load on my laptop, which tells me cert intercept may still be an issue. I will review more thoroughly later because I can get it to download and install patchily to run the web service directly, but I cannot get the init target to work and run it "in the pipeline" so to speak. Probably a local env issue on my end, but we should document that.

Otherwise, nice work, sir.

**Comment by wandmagic** [comment]
> Sorry there are some cert issues and it is slow to load on my laptop, which tells me cert intercept may still be an issue. I will review more thoroughly later because I can get it to download and install patchily to run the web service directly, but I cannot get the init target to work and run it "in the pipeline" so to speak. Probably a local env issue on my end, but we should document that.
> 
> Otherwise, nice work, sir.

are you able to try make configure and make test?

let me know how the console looks

**Comment by aj-stein-gsa** [comment]
> let me know how the console looks

```
 % make init
git submodule update --init --recursive
Installing node modules...
npm install

up to date, audited 373 packages in 659ms

61 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npx oscal@latest use latest
Installing version: 2.2.0
Downloading OSCAL CLI...
Downloading version 2.2.0 from https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.2.0/oscal-cli-enhanced-2.2.0-oscal-cli.zip
Extracting OSCAL CLI...
Setting executable permissions for CLI at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
Creating OSCAL CLI symlink: oscal-cli => /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
OSCAL CLI installed to /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli
Alias created at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/bin/oscal-cli
npx oscal@latest server update
Latest version: v1.0.0-SNAPSHOT-ca519b8-20241023173929
Downloading latest release from https://github.com/metaschema-framework/oscal-server/releases/download/v1.0.0-SNAPSHOT-ca519b8-20241023173929/oscal-server-1.0.0-SNAPSHOT.zip

Successfully downloaded latest release
Downloaded 51063475 bytes
Extracting OSCAL SERVER...
OSCAL server v1.0.0-SNAPSHOT-ca519b8-20241023173929 installed successfully
Executable: /Users/alexanderjstein/.oscal/v1.0.0-SNAPSHOT-ca519b8-20241023173929/bin/oscal-server
Alias created: /Users/alexanderjstein/.local/bin/oscal-server

up to date, audited 373 packages in 609ms

61 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npx oscal@latest use latest
Installing version: 2.2.0
Downloading OSCAL CLI...
Downloading version 2.2.0 from https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.2.0/oscal-cli-enhanced-2.2.0-oscal-cli.zip
Extracting OSCAL CLI...
Setting executable permissions for CLI at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
Creating OSCAL CLI symlink: oscal-cli => /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
OSCAL CLI installed to /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli
Alias created at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/bin/oscal-cli
npx oscal@latest server update
Latest version: v1.0.0-SNAPSHOT-ca519b8-20241023173929
Downloading latest release from https://github.com/metaschema-framework/oscal-server/releases/download/v1.0.0-SNAPSHOT-ca519b8-20241023173929/oscal-server-1.0.0-SNAPSHOT.zip



Successfully downloaded latest release
Downloaded 51063475 bytes
Extracting OSCAL SERVER...
OSCAL server v1.0.0-SNAPSHOT-ca519b8-20241023173929 installed successfully
Executable: /Users/alexanderjstein/.oscal/v1.0.0-SNAPSHOT-ca519b8-20241023173929/bin/oscal-server
Alias created: /Users/alexanderjstein/.local/bin/oscal-server
npx oscal@latest server start -bg
Starting server in background mode...
file:///home/mefedramp-automation/node_modules/oscal/dist/env.js:289
    throw new Error("OSCAL SERVER not found");
          ^

Error: OSCAL SERVER not found
    at findOscalServerPath (file:///home/mefedramp-automation/node_modules/oscal/dist/env.js:289:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startServer (file:///home/mefedramp-automation/node_modules/oscal/dist/server.js:123:33)
    at async Command.serverCommand (file:///home/mefedramp-automation/node_modules/oscal/dist/server.js:189:9)

Node.js v20.17.0
make: *** [init-content] Error 1
```

**Comment by wandmagic** [comment]
> > let me know how the console looks
> 
> ```
>  % make init
> git submodule update --init --recursive
> Installing node modules...
> npm install
> 
> up to date, audited 373 packages in 659ms
> 
> 61 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> npx oscal@latest use latest
> Installing version: 2.2.0
> Downloading OSCAL CLI...
> Downloading version 2.2.0 from https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.2.0/oscal-cli-enhanced-2.2.0-oscal-cli.zip
> Extracting OSCAL CLI...
> Setting executable permissions for CLI at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
> Creating OSCAL CLI symlink: oscal-cli => /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
> OSCAL CLI installed to /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli
> Alias created at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/bin/oscal-cli
> npx oscal@latest server update
> Latest version: v1.0.0-SNAPSHOT-ca519b8-20241023173929
> Downloading latest release from https://github.com/metaschema-framework/oscal-server/releases/download/v1.0.0-SNAPSHOT-ca519b8-20241023173929/oscal-server-1.0.0-SNAPSHOT.zip
> 
> Successfully downloaded latest release
> Downloaded 51063475 bytes
> Extracting OSCAL SERVER...
> OSCAL server v1.0.0-SNAPSHOT-ca519b8-20241023173929 installed successfully
> Executable: /Users/alexanderjstein/.oscal/v1.0.0-SNAPSHOT-ca519b8-20241023173929/bin/oscal-server
> Alias created: /Users/alexanderjstein/.local/bin/oscal-server
> 
> up to date, audited 373 packages in 609ms
> 
> 61 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> npx oscal@latest use latest
> Installing version: 2.2.0
> Downloading OSCAL CLI...
> Downloading version 2.2.0 from https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.2.0/oscal-cli-enhanced-2.2.0-oscal-cli.zip
> Extracting OSCAL CLI...
> Setting executable permissions for CLI at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
> Creating OSCAL CLI symlink: oscal-cli => /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli/bin/oscal-cli
> OSCAL CLI installed to /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/lib/node_modules/oscal-cli
> Alias created at /Users/alexanderjstein/.asdf/installs/nodejs/20.17.0/bin/oscal-cli
> npx oscal@latest server update
> Latest version: v1.0.0-SNAPSHOT-ca519b8-20241023173929
> Downloading latest release from https://github.com/metaschema-framework/oscal-server/releases/download/v1.0.0-SNAPSHOT-ca519b8-20241023173929/oscal-server-1.0.0-SNAPSHOT.zip
> 
> 
> 
> Successfully downloaded latest release
> Downloaded 51063475 bytes
> Extracting OSCAL SERVER...
> OSCAL server v1.0.0-SNAPSHOT-ca519b8-20241023173929 installed successfully
> Executable: /Users/alexanderjstein/.oscal/v1.0.0-SNAPSHOT-ca519b8-20241023173929/bin/oscal-server
> Alias created: /Users/alexanderjstein/.local/bin/oscal-server
> npx oscal@latest server start -bg
> Starting server in background mode...
> file:///home/mefedramp-automation/node_modules/oscal/dist/env.js:289
>     throw new Error("OSCAL SERVER not found");
>           ^
> 
> Error: OSCAL SERVER not found
>     at findOscalServerPath (file:///home/mefedramp-automation/node_modules/oscal/dist/env.js:289:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async startServer (file:///home/mefedramp-automation/node_modules/oscal/dist/server.js:123:33)
>     at async Command.serverCommand (file:///home/mefedramp-automation/node_modules/oscal/dist/server.js:189:9)
> 
> Node.js v20.17.0
> make: *** [init-content] Error 1
> ```

ok i think i need to change the default server install location, or you can add that alias to the path

**Comment by wandmagic** [comment]
ok @aj-stein-gsa  try again, i fallback to expected location if its not found

**Comment by aj-stein-gsa** [comment]
> ok @aj-stein-gsa try again, i fallback to expected location if its not found

That's fine, but my PATH is controlled dynamically by [`asdf`](https://asdf-vm.com/), so what do you recommend here?

**Pull request closed without merging**
