### PR TITLE
introduce metaquery script

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

This PR includes a simple command line script to help developers test metapath results

leveraging the new metaspath eval command and using JSDOM to find the XML content, developers can use

npm run mq "//user" and select a content item to run the metapath against

also aliased to make metaquery 

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- ~If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?~ N/A

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Review by aj-stein-gsa — CHANGES_REQUESTED** [review]
First off, some positive feedback: love this, it will be a game changer, for me at the very least!

Can you please add some brief explanation outside the PR message in the [CONRIBUTING.md docs](https://github.com/GSA/fedramp-automation/blob/65f2030d8ced4cf3174c2a7c7f6310ca9ee3cc6a/src/validations/constraints/CONTRIBUTING.md) for developers to know about?

**Comment by aj-stein-gsa** [comment]
Also just a heads up:

> npm run mq -e "//user" and select a content item to run the metapath against

If you directly pass `-e "query"` of any kind the script still prompts you for the query and `-e` argument anyway, should this pull it from the command and not ask you?

**Comment by wandmagic** [comment]
> Also just a heads up:
> 
> > npm run mq -e "//user" and select a content item to run the metapath against
> 
> If you directly pass `-e "query"` of any kind the script still prompts you for the query and `-e` argument anyway, should this pull it from the command and not ask you?

esper@XVII fedramp-automation % npm run mq "//location"

> fedramp-automation@0.0.1 mq
> node ./src/scripts/dev-metaschema-eval.js //location

? Select an XML file to query against: ssp-all-VALID.xml
Querying metapath: //location
Against file: /Users/esper/fedramp-automation/src/validations/constraints/content/ssp-all-VALID.xml
oscal-cli metaschema metapath eval -e "//location" -m ./vendor/oscal/src/metaschema/oscal_complete_metaschema.xml -i /Users/esper/fedramp-automation/src/validations/constraints/content/ssp-all-VALID.xml
metapath result: (file:/Users/esper/fedramp-automation/src/validations/constraints/content/ssp-all-VALID.xml#/system-security-plan/metadata[1]/location[1],file:/Users/esper/fedramp-automation/src/validations/constraints/content/ssp-all-VALID.xml#/system-security-plan/metadata[1]/location[2])
<location xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111112-0000-4000-9000-000000000003">
      <address>
        <country>US</country>
      </address>
      <prop name="data-center" value="aws-us-west-1" class="alternate" ns="https://fedramp.gov/ns/oscal"/>
    </location>
<location xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111112-0000-4000-9001-000000000009">
      <address>
        <country>US</country>
      </address>
      <prop name="data-center" value="dc-zone-1" class="primary" ns="https://fedramp.gov/ns/oscal"/>
    </location>
    
    yes it was an error in the description, its a positional argument, the -e is what the oscal-cli expects under the hood

**Comment by wandmagic** [comment]
> First off, some positive feedback: love this, it will be a game changer, for me at the very least!
> 
> Can you please add some brief explanation outside the PR message in the [CONRIBUTING.md docs](https://github.com/GSA/fedramp-automation/blob/65f2030d8ced4cf3174c2a7c7f6310ca9ee3cc6a/src/validations/constraints/CONTRIBUTING.md) for developers to know about?

OK i've added a little blurb about how to use the npm run mq command

**Review by aj-stein-gsa — APPROVED** [review]
Nice addition to the tools. ✅ 🚢 💥

**Review by aj-stein-gsa — APPROVED** [review]

**Pull request merged**
