### PR TITLE
oscal server workflows

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

Canary branch for testing server based workflow
### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### CODE REVIEW

**Comment by wandmagic** [comment]
it shluld be noted that windows server support is not there yet, needs to be fixed upstream, but we do fallback to cli on windows

**Comment by wandmagic** [comment]
I was able to resolve windows specific concerns

**Comment by wandmagic** [comment]
we might still want to merge this into a new branch called "canary" rather than develop until we have more testing from users and update docs on how to install and run the server

**Review by aj-stein-gsa — CHANGES_REQUESTED** [review]
I am more than happy to merge this, but can you rename the branch to align with others and something a little more descriptive? Call it something like `feature-oscal-server`.

I will close the PR because you cannot rename a branch and update the PR, ask me how I know (sadly tried in my more naïve days 😆 ).

**Comment by aj-stein-gsa** [comment]
See above, just rename the branch and we can pull it in.

**Pull request closed without merging**
